using System;
using System.Collections.Generic;
using System.Text;

namespace DataTypes.Records
{
    //Automatic properties get and set, constructour, ToString, Equals, GetHashCode,
    //are generated by the compiler
    public record PlayerInitSetup(int Health, int Mana, int Damage, int Lvl);
}
